In [2]:
import tensorflow as tf
t = tf.constant([[1,2,3],[4,5,6]])
t

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [3]:
#tensorflow는 대부분의 기본 수 연산이 가능하다.
t[:,1:]
t[..., 1, tf.newaxis]
t@tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]])>

In [4]:
#numpy와 혼합 사용도 가능함.
import numpy as np
a=np.array([2.,4.,5.])
tf.constant(a)
tf.square(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 4., 16., 25.])>

In [5]:
v = tf.Variable([[1.,2.,3.],[4.,5.,6.,]])
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [6]:
v.assign(2*v)
v[:,2].assign([0.,1.])
# v[1] = [7.,8.,9.]처럼 직접 수정은 불가능하

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  0.],
       [ 8., 10.,  1.]], dtype=float32)>

In [8]:
def create_huber(threshold) = 1.0:
    def huber_fn(y_true, y_pred):
    error = y_true - y_pred
    is_small_error = tf.abs(error) < threshold
    squared_loss = tf.square(error) / 2
    linear_loss = threshold * tf.abs(error) - threshold ** 2/2
    return tf.where(is_small_error, squared_loss, linear_loss)
return huber_fn

SyntaxError: expected ':' (93528642.py, line 1)

In [9]:
model.compile(loss = huber_fn, optimizer = "nadam")
model.fit(X_train, y_train, [...])

NameError: name 'model' is not defined

In [13]:
precision = tf.keras.metrics.Precision()
precision([0,1,1,1,0,1,0,1],[1,1,0,1,0,1,0,1]) # label, 예

<tf.Tensor: shape=(), dtype=float32, numpy=0.800000011920929>

In [14]:
import tensorflow as tf

In [15]:
X=tf.range(10) 
dataset = tf.data.Dataset.from_tensor_slices(X)# = tf.data.Dataset.range(10)
dataset
for item in dataset:
    print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


In [16]:
X_nested = {"a" : ([1,2,3], [4,5,6]), "b" : [7,8,9]}
dataset = tf.data.Dataset.from_tensor_slices(X_nested)
for item in dataset:
    print(item)

{'a': (<tf.Tensor: shape=(), dtype=int32, numpy=1>, <tf.Tensor: shape=(), dtype=int32, numpy=4>), 'b': <tf.Tensor: shape=(), dtype=int32, numpy=7>}
{'a': (<tf.Tensor: shape=(), dtype=int32, numpy=2>, <tf.Tensor: shape=(), dtype=int32, numpy=5>), 'b': <tf.Tensor: shape=(), dtype=int32, numpy=8>}
{'a': (<tf.Tensor: shape=(), dtype=int32, numpy=3>, <tf.Tensor: shape=(), dtype=int32, numpy=6>), 'b': <tf.Tensor: shape=(), dtype=int32, numpy=9>}


In [17]:
dataset = dataset.repeat(3).batch(7)
for item in dataset:
    print(item)

{'a': (<tf.Tensor: shape=(7,), dtype=int32, numpy=array([1, 2, 3, 1, 2, 3, 1])>, <tf.Tensor: shape=(7,), dtype=int32, numpy=array([4, 5, 6, 4, 5, 6, 4])>), 'b': <tf.Tensor: shape=(7,), dtype=int32, numpy=array([7, 8, 9, 7, 8, 9, 7])>}
{'a': (<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3])>, <tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 6])>), 'b': <tf.Tensor: shape=(2,), dtype=int32, numpy=array([8, 9])>}


In [18]:
dataset = dataset.map(lambda x :  x * 2)
for item in dataset:
    print(item)

TypeError: in user code:

    File "C:\Users\82106\AppData\Local\Temp\ipykernel_13400\453520087.py", line 1, in None  *
        lambda x :  x * 2

    TypeError: unsupported operand type(s) for *: 'dict' and 'int'


In [ ]:
dataset = dataset.filter(lambda x: tf.reduce_sum(x) > 50)
for item in dataset:
    print(item)

In [19]:
dataset = tf.data.Dataset.range(10).repeat(2)
dataset = dataset.shuffle(buffer_size = 4, seed=42).batch(7)
for item in dataset:
    print(item)

tf.Tensor([1 4 2 3 5 0 6], shape=(7,), dtype=int64)
tf.Tensor([9 8 2 0 3 1 4], shape=(7,), dtype=int64)
tf.Tensor([5 7 9 6 7 8], shape=(6,), dtype=int64)


In [ ]:
#데이터 전처리

In [ ]:
X_mean, X_std = [...]
n_inputs = 8
def parse_csv_line(line):
    defs = [0.] * n_inputs + [tf.constant([], dtype = tf.float32)]
    fields = tf.io.decode_csv(line, record_defaults = defs)
    return tf.stack(fields[:-1], tf.stack(fields[-1:])

def preprocess(line):
    x,y = parse_csv_line(line)
    return (x-X_mean) / X_std, y

In [ ]:
train_set = csv_reader_dataset(train_filepaths)
valid_set = csv_reader_dataset(valid_filepaths)
test_set = csv_reader_dataset(test_filepaths)

model = tf.keras.Sequential([...])
model.compile(loss = "mse", optimizer = "sgd")
model.fit(train_set, validation_data = valid_set,epochs = 5)

test_mse = model.evaluate(test_set)
new_set = test_set.take(3)
y_pred = model.predict(new_set)